In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("ventas_historicas.csv")

In [ ]:
#Carga el dataset y ejecuta los métodos de exploración inicial: shape, dtypes, head(),
#isnull().sum(). Documenta en una celda Markdown que observas sobre el dataset.

#Muestra la cantidad de columnas y filas que contiene el dataset
print(df.shape)

In [4]:
#El tipo de dato en cuanto a lo que relacione la columna del dataset
print(df.dtypes)

id_venta         int64
mes             object
region          object
vendedor        object
categoria       object
canal           object
cantidad         int64
precio_unit    float64
descuento      float64
monto_bruto    float64
dtype: object

In [5]:
#Se considera alguna muestra del dataset en sí, un "muestreo" por así decirlo.
print(df.head())

   id_venta    mes region      vendedor categoria   canal  cantidad  \
0      1001  Junio  Norte    Laura Diaz    Laptop  Online         4
1      1002  Enero  Oeste  Carlos Rivas    Laptop  Online         4
2      1003  Abril  Oeste    Laura Diaz    Tablet  Online        13
3      1004  Enero   Este   Camila Vega    Laptop  Online         6
4      1005  Enero  Norte    Laura Diaz   Teclado     NaN        10

   precio_unit  descuento  monto_bruto
0       769.94        0.0      3079.76
1       894.32        0.0      3577.28
2       375.14       15.0      4876.82
3      1010.65        NaN      6063.90
4        78.27        0.0       782.70

In [6]:
#La suma de los nulos del dataset
print(df.isnull().sum())

id_venta        0
mes             0
region          0
vendedor       21
categoria       0
canal          11
cantidad        0
precio_unit     0
descuento      11
monto_bruto     0
dtype: int64

In [13]:
#2. Filtra todas las ventas de la región 'Centro' con monto_bruto mayor a $300. Imprime cuantas filas cumplen esa condición.

center = df[(df['region'] == 'Centro') & (df['monto_bruto'] > 300)]
#Sintaxis de igual region con el centro y encadenar la condicion del monto bruno sobre $300
print(f"Filas que cumplen: {len(center)}")

Filas que cumplen: 47

In [14]:
df

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
0,1001,Junio,Norte,Laura Diaz,Laptop,Online,4,769.94,0.0,3079.76
1,1002,Enero,Oeste,Carlos Rivas,Laptop,Online,4,894.32,0.0,3577.28
2,1003,Abril,Oeste,Laura Diaz,Tablet,Online,13,375.14,15.0,4876.82
3,1004,Enero,Este,Camila Vega,Laptop,Online,6,1010.65,NaN,6063.90
4,1005,Enero,Norte,Laura Diaz,Teclado,NaN,10,78.27,0.0,782.70
...,...,...,...,...,...,...,...,...,...,...
295,1296,Abril,Sur,Carlos Rivas,Teclado,Online,8,71.84,0.0,574.72
296,1297,Abril,Este,Camila Vega,Tablet,Tienda fisica,9,359.42,20.0,3234.78
297,1298,Enero,Centro,Laura Diaz,Laptop,Online,1,1036.18,20.0,1036.18
298,1299,Junio,Oeste,Camila Vega,Teclado,Online,11,69.20,10.0,761.20
299,1300,Mayo,Sur,Javier Munoz,Tablet,Tienda fisica,10,353.19,20.0,3531.90

In [21]:
#3. Filtra las ventas del canal 'Online' cuyo descuento sea mayor o igual a 15. Muestra solo las
#columnas: region, categoria, cantidad, monto_bruto, descuento.

descuento = df[df['mes'].isin(['Enero', 'Febrero']) & df['categoria'].isin(['Laptop', 'Tablet']) & (df['descuento'] >= 15)]

print(descuento)

     id_venta      mes  region         vendedor categoria          canal  \
15       1016  Febrero  Centro  Roberto Fuentes    Tablet      Mayorista
23       1024  Febrero   Oeste      Camila Vega    Laptop         Online
149      1150  Febrero   Oeste      Maria Lopez    Tablet         Online
157      1158  Febrero    Este       Ana Torres    Tablet  Tienda fisica
187      1188  Febrero   Oeste     Javier Munoz    Tablet      Mayorista
297      1298    Enero  Centro       Laura Diaz    Laptop         Online

     cantidad  precio_unit  descuento  monto_bruto
15          3       305.93       20.0       917.79
23          7       812.67       20.0      5688.69
149         2       309.86       20.0       619.72
157        15       378.21       15.0      5673.15
187        12       312.03       20.0      3744.36
297         1      1036.18       20.0      1036.18

In [23]:
#Filtra ventas donde la categoría sea 'Laptop' o 'Tablet', usando .isin(). ¿Cuantas filas resultan?

reporte = df.groupby('region')['monto_bruto'].agg(Total='sum', Promedio='mean', Maximo='max', Minimo='min', Conteo='count').round(2).reset_index()
print(reporte)

   region      Total  Promedio    Maximo  Minimo  Conteo
0  Centro  110254.74   1934.29  13576.05   34.07      57
1    Este  147358.93   2585.24  12010.88   69.24      57
2   Norte  167154.38   2932.53  15186.30   33.77      57
3   Oeste  183789.62   2588.59  14492.25   31.32      71
4     Sur  120768.25   2082.21  14657.40   34.20      58

In [30]:
#Filtra ventas con cantidad entre 8 y 15 unidades (inclusive), usando .between(). Muestra las primeras 10 filas ordenadas de mayor a menor monto_bruto.
# 5. Cantidad entre 8 y 15 unidades
filtro_ventas = df[df['cantidad'].between(8, 15)]
print(filtro_ventas.sort_values('monto_bruto').head(10))

     id_venta    mes  region         vendedor categoria          canal  \
195      1196  Marzo   Oeste       Ana Torres     Mouse      Mayorista
189      1190  Junio   Oeste  Roberto Fuentes     Mouse  Tienda fisica
73       1074  Marzo   Norte  Roberto Fuentes     Mouse  Tienda fisica
83       1084  Abril     Sur  Roberto Fuentes     Mouse         Online
76       1077  Abril    Este       Laura Diaz     Mouse      Mayorista
160      1161   Mayo   Oeste       Ana Torres     Mouse      Mayorista
161      1162  Abril     Sur              NaN     Mouse      Mayorista
208      1209  Enero  Centro     Javier Munoz     Mouse  Tienda fisica
224      1225  Junio   Oeste       Ana Torres     Mouse         Online
125      1126  Marzo    Este     Javier Munoz     Mouse         Online

     cantidad  precio_unit  descuento  monto_bruto
195         8        33.47       15.0       267.76
189         9        29.86        0.0       268.74
73          8        34.52        0.0       276.16
83          8        34.62        0.0       276.96
76         10        30.59       15.0       305.90
160         9        37.80       15.0       340.20
161        11        30.95        0.0       340.45
208         8        43.60       10.0       348.80
224        12        30.37        5.0       364.44
125        10        36.85        0.0       368.50

In [ ]:
#1. Porque son condicionales vectorizadas, el "and" y el "or" se ocupan para veracidad como tal de verdadero y/o falso.

#2. El código es más limpio, visualizable y legible netamente.

In [32]:
#Ejercicio 2

#Filtra ventas realizadas en 'Enero' o 'Febrero', donde la categoría sea 'Laptop' o 'Tablet', y el
#descuento sea mayor a 10. Usa una sola expresión de filtro.

descuento2 = df[df['mes'].isin(['Enero', 'Febrero']) & df['categoria'].isin(['Laptop', 'Tablet']) & (df['descuento'] >= 10)]
print(descuento2)

     id_venta      mes  region         vendedor categoria          canal  \
13       1014  Febrero  Centro     Javier Munoz    Tablet         Online
15       1016  Febrero  Centro  Roberto Fuentes    Tablet      Mayorista
23       1024  Febrero   Oeste      Camila Vega    Laptop         Online
149      1150  Febrero   Oeste      Maria Lopez    Tablet         Online
157      1158  Febrero    Este       Ana Torres    Tablet  Tienda fisica
158      1159    Enero  Centro       Ana Torres    Laptop  Tienda fisica
187      1188  Febrero   Oeste     Javier Munoz    Tablet      Mayorista
247      1248    Enero    Este      Camila Vega    Laptop         Online
297      1298    Enero  Centro       Laura Diaz    Laptop         Online

     cantidad  precio_unit  descuento  monto_bruto
13          9       394.05       10.0      3546.45
15          3       305.93       20.0       917.79
23          7       812.67       20.0      5688.69
149         2       309.86       20.0       619.72
157        15       378.21       15.0      5673.15
158         4      1006.39       10.0      4025.56
187        12       312.03       20.0      3744.36
247        14       748.35       10.0     10476.90
297         1      1036.18       20.0      1036.18

In [35]:
# Del resultado anterior, identifica los 5 registros con mayor monto_bruto. Usa .nlargest(5,'monto_bruto') o .sort_values().head(5).
registro_mayor = df.nlargest(5,'monto_bruto')
print(registro_mayor)

     id_venta      mes  region         vendedor categoria          canal  \
25       1026     Mayo   Norte              NaN    Laptop      Mayorista
207      1208    Abril     Sur  Roberto Fuentes    Laptop            NaN
88       1089    Junio   Oeste      Maria Lopez    Laptop  Tienda fisica
47       1048  Febrero   Norte  Roberto Fuentes    Laptop      Mayorista
11       1012    Junio  Centro     Carlos Rivas    Laptop      Mayorista

     cantidad  precio_unit  descuento  monto_bruto
25         15      1012.42        0.0     15186.30
207        15       977.16       20.0     14657.40
88         15       966.15       10.0     14492.25
47         14       983.79        5.0     13773.06
11         15       905.07        0.0     13576.05

In [42]:
#Crea un nuevo filtro para ventas de la region 'Norte' o 'Sur', con cantidad mayor o igual a 10
#unidades y monto_bruto superior al promedio general de monto_bruto del dataset. (Calcula
#el promedio con df['monto_bruto'].mean())

promedio=df['monto_bruto'].mean()

nuevo_filtro = df[df['region'].isin(['Norte', 'Sur']) & (df['cantidad'] >= 10) & (df['monto_bruto'] > promedio)]
print(nuevo_filtro)

     id_venta      mes region         vendedor categoria          canal  \
25       1026     Mayo  Norte              NaN    Laptop      Mayorista
36       1037    Abril    Sur       Ana Torres    Tablet         Online
37       1038  Febrero    Sur     Carlos Rivas   Monitor  Tienda fisica
42       1043    Abril    Sur     Carlos Rivas   Monitor      Mayorista
46       1047     Mayo  Norte     Javier Munoz   Monitor         Online
47       1048  Febrero  Norte  Roberto Fuentes    Laptop      Mayorista
59       1060  Febrero  Norte       Pedro Soto    Laptop         Online
62       1063    Junio    Sur       Laura Diaz    Laptop      Mayorista
75       1076     Mayo    Sur      Camila Vega    Laptop      Mayorista
114      1115    Marzo  Norte       Pedro Soto    Laptop         Online
115      1116  Febrero    Sur       Ana Torres   Monitor  Tienda fisica
116      1117    Enero  Norte     Javier Munoz    Tablet         Online
123      1124    Abril  Norte     Carlos Rivas    Laptop      Mayorista
165      1166  Febrero    Sur       Ana Torres    Laptop  Tienda fisica
207      1208    Abril    Sur  Roberto Fuentes    Laptop            NaN
211      1212  Febrero  Norte  Roberto Fuentes    Tablet  Tienda fisica
223      1224    Junio  Norte      Camila Vega    Laptop      Mayorista
225      1226     Mayo  Norte       Laura Diaz    Tablet         Online
264      1265    Abril  Norte     Carlos Rivas   Monitor         Online
266      1267    Marzo  Norte     Carlos Rivas    Laptop      Mayorista
281      1282    Abril  Norte       Ana Torres    Tablet  Tienda fisica
299      1300     Mayo    Sur     Javier Munoz    Tablet  Tienda fisica

     cantidad  precio_unit  descuento  monto_bruto
25         15      1012.42        0.0     15186.30
36         12       390.33       20.0      4683.96
37         14       250.99        5.0      3513.86
42         15       284.80        0.0      4272.00
46         14       356.93        0.0      4997.02
47         14       983.79        5.0     13773.06
59         10       774.31        0.0      7743.10
62         10       996.38       20.0      9963.80
75         10       991.35        0.0      9913.50
114        13       914.46        0.0     11887.98
115        14       360.65        0.0      5049.10
116        10       313.44        0.0      3134.40
123        12       849.20        0.0     10190.40
165        15       827.93        5.0     12418.95
207        15       977.16       20.0     14657.40
211        15       303.75        0.0      4556.25
223        13      1040.82        0.0     13530.66
225        14       389.30       10.0      5450.20
264        14       355.62        0.0      4978.68
266        13       778.38       15.0     10118.94
281        14       355.95       15.0      4983.30
299        10       353.19       20.0      3531.90

In [55]:
#Compara: cuantas ventas existen por región usando el filtro del paso 3 vs. sin aplicar el filtro
#de cantidad mínima. Usa .value_counts() sobre la columna región en cada caso.

df_filtrado2 = df[df['region'].isin(['Norte', 'Sur']) & (df['monto_bruto'] > promedio)]
print("CON FILTRO")
print(nuevo_filtro['region'].value_counts())
print("SIN FILTRO")
print(df_filtrado2['region'].value_counts())

CON FILTRO
region
Norte    13
Sur       9
Name: count, dtype: int64
SIN FILTRO
region
Norte    17
Sur      13
Name: count, dtype: int64

In [52]:
df_filtrado2

,id_venta,mes,region,vendedor,categoria,canal,cantidad,precio_unit,descuento,monto_bruto
0,1001,Junio,Norte,Laura Diaz,Laptop,Online,4,769.94,0.0,3079.76
10,1011,Junio,Norte,Maria Lopez,Tablet,Mayorista,7,348.34,5.0,2438.38
25,1026,Mayo,Norte,NaN,Laptop,Mayorista,15,1012.42,0.0,15186.30
36,1037,Abril,Sur,Ana Torres,Tablet,Online,12,390.33,20.0,4683.96
37,1038,Febrero,Sur,Carlos Rivas,Monitor,Tienda fisica,14,250.99,5.0,3513.86
41,1042,Enero,Sur,Camila Vega,Monitor,Online,9,353.87,10.0,3184.83
42,1043,Abril,Sur,Carlos Rivas,Monitor,Mayorista,15,284.80,0.0,4272.00
46,1047,Mayo,Norte,Javier Munoz,Monitor,Online,14,356.93,0.0,4997.02
47,1048,Febrero,Norte,Roberto Fuentes,Laptop,Mayorista,14,983.79,5.0,13773.06
49,1050,Junio,Sur,Roberto Fuentes,Tablet,Online,9,303.90,20.0,2735.10
59,1060,Febrero,Norte,Pedro Soto,Laptop,Online,10,774.31,0.0,7743.10
62,1063,Junio,Sur,Laura Diaz,Laptop,Mayorista,10,996.38,20.0,9963.80
75,1076,Mayo,Sur,Camila Vega,Laptop,Mayorista,10,991.35,0.0,9913.50
114,1115,Marzo,Norte,Pedro Soto,Laptop,Online,13,914.46,0.0,11887.98
115,1116,Febrero,Sur,Ana Torres,Monitor,Tienda fisica,14,360.65,0.0,5049.10
116,1117,Enero,Norte,Javier Munoz,Tablet,Online,10,313.44,0.0,3134.40
123,1124,Abril,Norte,Carlos Rivas,Laptop,Mayorista,12,849.20,0.0,10190.40
137,1138,Mayo,Sur,Carlos Rivas,Laptop,Mayorista,9,788.43,20.0,7095.87
165,1166,Febrero,Sur,Ana Torres,Laptop,Tienda fisica,15,827.93,5.0,12418.95
170,1171,Junio,Norte,Camila Vega,Laptop,Tienda fisica,9,994.87,NaN,8953.83
173,1174,Junio,Norte,Maria Lopez,Laptop,Tienda fisica,9,854.08,10.0,7686.72
180,1181,Marzo,Sur,NaN,Tablet,Tienda fisica,9,386.55,20.0,3478.95
207,1208,Abril,Sur,Roberto Fuentes,Laptop,NaN,15,977.16,20.0,14657.40
211,1212,Febrero,Norte,Roberto Fuentes,Tablet,Tienda fisica,15,303.75,0.0,4556.25
223,1224,Junio,Norte,Camila Vega,Laptop,Mayorista,13,1040.82,0.0,13530.66
225,1226,Mayo,Norte,Laura Diaz,Tablet,Online,14,389.30,10.0,5450.20
264,1265,Abril,Norte,Carlos Rivas,Monitor,Online,14,355.62,0.0,4978.68
266,1267,Marzo,Norte,Carlos Rivas,Laptop,Mayorista,13,778.38,15.0,10118.94
281,1282,Abril,Norte,Ana Torres,Tablet,Tienda fisica,14,355.95,15.0,4983.30
299,1300,Mayo,Sur,Javier Munoz,Tablet,Tienda fisica,10,353.19,20.0,3531.90

In [57]:
#Crea una función Python que reciba como parámetros: region, categoria y monto_minimo,
#y retorne el DataFrame filtrado según esos criterios. Pruébala con al menos 3 combinaciones
#diferentes.

def filtrar_ventas(region, categoria, monto_minimo):
    resultado = df[
        (df['region'] == region) & 
        (df['categoria'] == categoria) & 
        (df['monto_bruto'] >= monto_minimo)
    ]
    return resultado

# Pruebas con distintas combinaciones
prueba_1 = filtrar_ventas('Centro', 'Laptop', 5000)
prueba_2 = filtrar_ventas('Sur', 'Monitor', 1000)
prueba_3 = filtrar_ventas('Norte', 'Auriculares', 500)

print(f"Ventas encontradas Prueba 1: {prueba_1.shape[0]}")
print(f"Ventas encontradas Prueba 2: {prueba_2.shape[0]}")
print(f"Ventas encontradas Prueba 3: {prueba_3.shape[0]}")

Ventas encontradas Prueba 1: 2
Ventas encontradas Prueba 2: 11
Ventas encontradas Prueba 3: 12

In [60]:
#Ejercicio 3 

# Agrupa el dataset por 'region' y calcula para la columna monto_bruto: suma total,
#promedio, máximo, mínimo y conteo de transacciones. Usa .agg() con nombres de
#columnas personalizados y aplica. round(2).

resumen_region = df.groupby('region').agg(
    suma_total=('monto_bruto', 'sum'),
    promedio=('monto_bruto', 'mean'),
    maximo=('monto_bruto', 'max'),
    minimo=('monto_bruto', 'min'),
    conteo=('monto_bruto', 'count')
).round(2) # 2 decimaless

In [61]:
# 2. Sobre el resultado anterior, usa .reset_index() y ordena de mayor a menor según el total de
#ventas. Muestra el DataFrame resultante.

resumen_region = resumen_region.reset_index().sort_values(by='suma_total')

print(resumen_region)

   region  suma_total  promedio    maximo  minimo  conteo
0  Centro   110254.74   1934.29  13576.05   34.07      57
4     Sur   120768.25   2082.21  14657.40   34.20      58
1    Este   147358.93   2585.24  12010.88   69.24      57
2   Norte   167154.38   2932.53  15186.30   33.77      57
3   Oeste   183789.62   2588.59  14492.25   31.32      71

In [66]:
#3. Agrupa por ['region', 'mes'] y calcula la suma de monto_bruto y la suma de cantidad. Usa
#reset_index() al final. Muestra las primeras 10 filas

agrupacion = df.groupby(['region', 'mes'])[['monto_bruto', 'cantidad']].sum().reset_index()
print(agrupacion)

    region      mes  monto_bruto  cantidad
0   Centro    Abril     10390.50        64
1   Centro    Enero      8727.16        33
2   Centro  Febrero      6330.77        37
3   Centro    Junio     51903.36       120
4   Centro    Marzo     16884.87        81
5   Centro     Mayo     16018.08        62
6     Este    Abril     29469.73       111
7     Este    Enero     21131.64        64
8     Este  Febrero     25411.30        56
9     Este    Junio     25126.33        60
10    Este    Marzo     13920.69        67
11    Este     Mayo     32299.24        90
12   Norte    Abril     29019.38       124
13   Norte    Enero      5588.67        36
14   Norte  Febrero     29335.57        69
15   Norte    Junio     42657.28       102
16   Norte    Marzo     27532.04        80
17   Norte     Mayo     33021.44       111
18   Oeste    Abril     35644.34       135
19   Oeste    Enero     16936.80        61
20   Oeste  Febrero     57842.95       125
21   Oeste    Junio     33062.70        96
22   Oeste    Marzo     16948.56        66
23   Oeste     Mayo     23354.27        95
24     Sur    Abril     33201.05       130
25     Sur    Enero     15321.54        97
26     Sur  Febrero     21079.02        46
27     Sur    Junio     15081.79        44
28     Sur    Marzo      9099.19        47
29     Sur     Mayo     26985.66        89

In [68]:
#4. Identifica el vendedor con mayor suma de monto_bruto (ignorando nulos con dropna=False
#por defecto en groupby). Usa .groupby('vendedor')['monto_bruto'].sum().idxmax() para
#encontrar el nombre directamente

mejor_vendedor = df.groupby('vendedor', dropna=False)['monto_bruto'].sum().idxmax()

print(f"El vendedor con el mayor monto bruto de ventas es: {mejor_vendedor}")

El vendedor con el mayor monto bruto de ventas es: Camila Vega

In [70]:
#5. Agrupa por categoría y calcula el precio_unit promedio y la cantidad total. Ordena por
#precio promedio descendente e interpreta el resultado: ¿que categoría tiene el mayor
#ticket promedio?

# 5. Agrupar por categoría: precio promedio y cantidad total
resumen_categoria = df.groupby('categoria').agg(precio_promedio=('precio_unit', 'mean'), cantidad_total=('cantidad', 'sum')).round(2).sort_values(by='precio_promedio', ascending=False)

print(resumen_categoria)

             precio_promedio  cantidad_total
categoria
Laptop                905.99             428
Tablet                332.04             405
Monitor               307.31             333
Auriculares           126.98             516
Teclado                68.89             445
Mouse                  36.55             271

In [ ]:
#Preguntas de Reflexion
#1. Para que sirve .reset_index() despues de un groupby? ¿Que sucede si no lo aplicas?
#2. Cuando es preferible .agg() con nombres vs. usar .sum(), .mean() directamente?

#1. Sirve principalmente para convertir los indices del dataframe en columnas utilizables
#2. agg sirve para agrupar multiples funciones, el otro es en únicas ocasiones puntuales que se requiera sacar uno individualmente.

In [75]:
#Ejercicio 4

#1. Crea una tabla pivote usando pd.pivot_table() con: indice = 'region', columnas = 'mes',
#valores = 'monto_bruto', funcion de agregación = suma. Aplica .round(2) al resultado.

pivoteo=pd.pivot_table(df,index='region',columns='mes',values='monto_bruto',aggfunc='sum').round(2)
print(pivoteo)

mes        Abril     Enero   Febrero     Junio     Marzo      Mayo
region
Centro  10390.50   8727.16   6330.77  51903.36  16884.87  16018.08
Este    29469.73  21131.64  25411.30  25126.33  13920.69  32299.24
Norte   29019.38   5588.67  29335.57  42657.28  27532.04  33021.44
Oeste   35644.34  16936.80  57842.95  33062.70  16948.56  23354.27
Sur     33201.05  15321.54  21079.02  15081.79   9099.19  26985.66

In [78]:
#2. Sobre la tabla pivote, usa .fillna(0) para reemplazar los valores NaN por 0. Explica en
#Markdown por que pueden existir NaN en una pivot_table.
pivoteo = pivoteo.fillna(0)
print(pivoteo)

mes        Abril     Enero   Febrero     Junio     Marzo      Mayo
region
Centro  10390.50   8727.16   6330.77  51903.36  16884.87  16018.08
Este    29469.73  21131.64  25411.30  25126.33  13920.69  32299.24
Norte   29019.38   5588.67  29335.57  42657.28  27532.04  33021.44
Oeste   35644.34  16936.80  57842.95  33062.70  16948.56  23354.27
Sur     33201.05  15321.54  21079.02  15081.79   9099.19  26985.66

In [92]:
#3. Agrega una columna de totales al final de la tabla pivote usando pivot['Total'] =
#pivot.sum(axis=1). ¿Cuál es la región con mayor total semestral?
pivoteo['Total'] = pivoteo.sum(axis=1)

pivoteo
#La región es la del oste como tal
region_max_total = pivoteo['Total'].idxmax()
print("La region con más ventas es:", region_max_total)

La region con más ventas es: Oeste

In [89]:
#4. Aplica formato de estilo con pivot.style.format('${:,.2f}').highlight_max(axis=0, color='#E8F8F5')
#para resaltar el maximo de cada mes por columna.

region_max_total = pivoteo['Total'].idxmax()
print(f"La región con el mayor total semestral es: {region_max_total}")

La región con el mayor total semestral es: Oeste

In [86]:
#5. Crea una segunda pivot_table donde el indice sea 'categoria' y las columnas sean 'canal'.
#Usa aggfunc='count' para contar el numero de transacciones por combinación. ¿Que
#canal tiene mas ventas para Laptops?

pivote_canal_categoria= pd.pivot_table(df,index='categoria',columns='canal',values='id_venta', aggfunc='count')

print(pivote_canal_categoria)

# Pregunta 5: ¿Qué canal tiene más ventas para Laptops?
canal_max_laptops = pivot_categoria_canal.loc['Laptop'].idxmax()
print(f"El canal con más ventas para Laptops es: {canal_max_laptops}")

canal        Mayorista  Online  Tienda fisica
categoria
Auriculares         16      24             17
Laptop              17      13             16
Monitor             12      17             15
Mouse               13      12             19
Tablet              16      14             18
Teclado             18      18             14
El canal con más ventas para Laptops es: Mayorista