In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [103]:
print(pd.__version__)

2.2.2

In [104]:
#Ejercicio 1
import pandas as pd
df = pd.read_csv("clima_talca_enero2024.csv")

In [105]:
df

         fecha  temp_max  temp_min  humedad_pct  precipitacion_mm condicion
0   2024-01-01      32.1      18.2         45.0               0.0   Soleado
1   2024-01-02      33.5      17.5         48.0               0.0   Soleado
2   2024-01-03       NaN      19.0         42.0               0.0   Parcial
3   2024-01-04      31.8       NaN         50.0               0.0   Soleado
4   2024-01-05      34.2      17.8          NaN               0.0   Soleado
5   2024-01-06      35.0      18.5         44.0               0.0  Caluroso
6   2024-01-07       NaN      19.2         47.0               NaN  Caluroso
7   2024-01-08      33.1       NaN         51.0               0.0   Parcial
8   2024-01-09      30.5      16.5         55.0               2.5   Nublado
9   2024-01-10      29.8      17.1         53.0               1.8  Lluvioso
10  2024-01-11      31.2      18.3         49.0               0.0  Lluvioso
11  2024-01-12       NaN      17.9         46.0               0.0   Parcial
12  2024-01-13      33.7       NaN         48.0               0.0   Soleado
13  2024-01-14      34.9      18.7          NaN               0.0   Soleado
14  2024-01-15      35.4      19.1         43.0               0.0  Caluroso
15  2024-01-16       NaN      18.0         45.0               0.0  Caluroso
16  2024-01-17      32.6       NaN         50.0               NaN       NaN
17  2024-01-18      31.0      17.3         52.0               0.0   Parcial
18  2024-01-19      30.2      16.8         54.0               0.0   Nublado
19  2024-01-20      29.5      17.5         56.0               0.0   Nublado
20  2024-01-21      28.8      16.2         58.0               0.0  Lluvioso
21  2024-01-22       NaN      17.0         55.0               3.2  Lluvioso
22  2024-01-23      31.5       NaN         52.0               1.5   Parcial
23  2024-01-24      33.2      18.1          NaN               0.0   Soleado
24  2024-01-25      34.0      17.6         47.0               0.0   Soleado
25  2024-01-26      35.1      18.9         44.0               0.0  Caluroso
26  2024-01-27       NaN      19.3         42.0               0.0  Caluroso
27  2024-01-28      32.8       NaN         46.0               NaN       NaN
28  2024-01-29      31.4      17.2         49.0               0.0   Parcial
29  2024-01-30      30.7      16.9         51.0               0.0   Nublado
30  2024-01-31      29.9      17.4         53.0               0.0   Soleado

In [106]:
print(df.shape)
print(df.isnull().sum())

(31, 6)
fecha               0
temp_max            6
temp_min            6
humedad_pct         3
precipitacion_mm    3
condicion           2
dtype: int64

In [107]:
#Ejecuta los métodos de exploración: head(5), tail(3), info(), describe() y shape.
print(df.head(5))

        fecha  temp_max  temp_min  humedad_pct  precipitacion_mm condicion
0  2024-01-01      32.1      18.2         45.0               0.0   Soleado
1  2024-01-02      33.5      17.5         48.0               0.0   Soleado
2  2024-01-03       NaN      19.0         42.0               0.0   Parcial
3  2024-01-04      31.8       NaN         50.0               0.0   Soleado
4  2024-01-05      34.2      17.8          NaN               0.0   Soleado

In [108]:
print(df.tail(3))

         fecha  temp_max  temp_min  humedad_pct  precipitacion_mm condicion
28  2024-01-29      31.4      17.2         49.0               0.0   Parcial
29  2024-01-30      30.7      16.9         51.0               0.0   Nublado
30  2024-01-31      29.9      17.4         53.0               0.0   Soleado

In [109]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha             31 non-null     object
 1   temp_max          25 non-null     float64
 2   temp_min          25 non-null     float64
 3   humedad_pct       28 non-null     float64
 4   precipitacion_mm  28 non-null     float64
 5   condicion         29 non-null     object
dtypes: float64(4), object(2)
memory usage: 1.6+ KB
None

In [110]:
print(df.describe())

        temp_max  temp_min  humedad_pct  precipitacion_mm
count  25.000000  25.00000    28.000000         28.000000
mean   32.236000  17.84000    49.107143          0.321429
std     1.936896   0.87892     4.433369          0.840792
min    28.800000  16.20000    42.000000          0.000000
25%    30.700000  17.20000    45.750000          0.000000
50%    32.100000  17.80000    49.000000          0.000000
75%    33.700000  18.50000    52.250000          0.000000
max    35.400000  19.30000    58.000000          3.200000

In [111]:
print(df.shape)

(31, 6)

In [24]:
#Hallazgos principales: El dataset posee 31 filas y 6 columnas de datos dados en temp_max, temp_min, humedad_pct
#y precipitaciones_mm. Contiene datos decimales (float), fecha, object (fecha) y datos NaN. 

#Preguntas de reflexión:
#Hay 31 filas y 6 columnas en el dataset analizado.
#4 tipos de indice poseen datos float, siendo estos temp_max, temp_min, humedad_pct y precipitaciones_mm
#La temp_max promedio según describe es de "35.400000".
#Info entrega datos de columnas (Un total de 6 según texto info) y 31 filas. Da una muestra de 5 primeras filas, nos indica el tipo que es
#Además de la memoria que usa, además entrega el tipo de dato que es si es float o objeto.

In [112]:
#Ejercicio 2
df.isnull().sum()

fecha               0
temp_max            6
temp_min            6
humedad_pct         3
precipitacion_mm    3
condicion           2
dtype: int64

In [113]:
porcentaje_nulos = (df.isnull().sum() / len(df)) * 100

In [114]:
#Para el 15%
#las columnas que superan el 15%
columnas_porcentual = porcentaje_nulos[porcentaje_nulos > 15]
#printeo
print(columnas_porcentual)

temp_max    19.354839
temp_min    19.354839
dtype: float64

In [ ]:
#temp_max    19.354839
#temp_min    19.354839
#dtype: float64

In [ ]:
#P2.1: Faltan 20 datos NaN.
#P2.2: Para demostrar si temperatura maxima y mínima con un 19% superior, la importancia de esto básicamente rádica en el tipo de limpieza que deba hacerse al 
#dataset, siendo más efectivo el rellenar los NaN o directamente eliminar las filas con datos corruptos
#P2.3: Porque creo que es un resultado más directo, dado que si entregan 100 datos nulos como tal en total, no me daría una respuesta significativa a si en realidad que método usar, en cambio si 
#me entregaran un "10%" me entregaría una cifra significativa para poder utilizar una limpieza efectiva sobre el dataset.

In [119]:
#Ejercicio 3
df_limpio = df.copy()
df_limpio

         fecha  temp_max  temp_min  humedad_pct  precipitacion_mm condicion
0   2024-01-01      32.1      18.2         45.0               0.0   Soleado
1   2024-01-02      33.5      17.5         48.0               0.0   Soleado
2   2024-01-03       NaN      19.0         42.0               0.0   Parcial
3   2024-01-04      31.8       NaN         50.0               0.0   Soleado
4   2024-01-05      34.2      17.8          NaN               0.0   Soleado
5   2024-01-06      35.0      18.5         44.0               0.0  Caluroso
6   2024-01-07       NaN      19.2         47.0               NaN  Caluroso
7   2024-01-08      33.1       NaN         51.0               0.0   Parcial
8   2024-01-09      30.5      16.5         55.0               2.5   Nublado
9   2024-01-10      29.8      17.1         53.0               1.8  Lluvioso
10  2024-01-11      31.2      18.3         49.0               0.0  Lluvioso
11  2024-01-12       NaN      17.9         46.0               0.0   Parcial
12  2024-01-13      33.7       NaN         48.0               0.0   Soleado
13  2024-01-14      34.9      18.7          NaN               0.0   Soleado
14  2024-01-15      35.4      19.1         43.0               0.0  Caluroso
15  2024-01-16       NaN      18.0         45.0               0.0  Caluroso
16  2024-01-17      32.6       NaN         50.0               NaN       NaN
17  2024-01-18      31.0      17.3         52.0               0.0   Parcial
18  2024-01-19      30.2      16.8         54.0               0.0   Nublado
19  2024-01-20      29.5      17.5         56.0               0.0   Nublado
20  2024-01-21      28.8      16.2         58.0               0.0  Lluvioso
21  2024-01-22       NaN      17.0         55.0               3.2  Lluvioso
22  2024-01-23      31.5       NaN         52.0               1.5   Parcial
23  2024-01-24      33.2      18.1          NaN               0.0   Soleado
24  2024-01-25      34.0      17.6         47.0               0.0   Soleado
25  2024-01-26      35.1      18.9         44.0               0.0  Caluroso
26  2024-01-27       NaN      19.3         42.0               0.0  Caluroso
27  2024-01-28      32.8       NaN         46.0               NaN       NaN
28  2024-01-29      31.4      17.2         49.0               0.0   Parcial
29  2024-01-30      30.7      16.9         51.0               0.0   Nublado
30  2024-01-31      29.9      17.4         53.0               0.0   Soleado

In [130]:
df_limpio['temp_max'] = df_limpio['temp_max'].fillna(df_limpio['temp_max'].mean())
df_limpio['temp_min'] = df_limpio['temp_min'].fillna(df_limpio['temp_min'].mean())

df_limpio['humedad_pct'] = df_limpio['humedad_pct'].fillna(df_limpio['humedad_pct'].median())

df_limpio['precipitacion_mm'] = df_limpio['precipitacion_mm'].fillna(0.0)

filas_antes = len(df_limpio)
df_limpio.dropna(subset=['condicion'], inplace=True)
filas_despues = len(df_limpio)

print("Resumen de nulos después de la limpieza:")
print(df_limpio.isnull().sum())

Resumen de nulos después de la limpieza:
fecha               0
temp_max            0
temp_min            0
humedad_pct         0
precipitacion_mm    0
condicion           0
dtype: int64

In [129]:
limpieza = df_limpio.isnull().sum()
print(limpieza)
df_limpio

fecha               0
temp_max            0
temp_min            0
humedad_pct         0
precipitacion_mm    0
condicion           0
dtype: int64

         fecha  temp_max  temp_min  humedad_pct  precipitacion_mm condicion
0   2024-01-01    32.100     18.20         45.0               0.0   Soleado
1   2024-01-02    33.500     17.50         48.0               0.0   Soleado
2   2024-01-03    32.236     19.00         42.0               0.0   Parcial
3   2024-01-04    31.800     17.84         50.0               0.0   Soleado
4   2024-01-05    34.200     17.80         49.0               0.0   Soleado
5   2024-01-06    35.000     18.50         44.0               0.0  Caluroso
6   2024-01-07    32.236     19.20         47.0               0.0  Caluroso
7   2024-01-08    33.100     17.84         51.0               0.0   Parcial
8   2024-01-09    30.500     16.50         55.0               2.5   Nublado
9   2024-01-10    29.800     17.10         53.0               1.8  Lluvioso
10  2024-01-11    31.200     18.30         49.0               0.0  Lluvioso
11  2024-01-12    32.236     17.90         46.0               0.0   Parcial
12  2024-01-13    33.700     17.84         48.0               0.0   Soleado
13  2024-01-14    34.900     18.70         49.0               0.0   Soleado
14  2024-01-15    35.400     19.10         43.0               0.0  Caluroso
15  2024-01-16    32.236     18.00         45.0               0.0  Caluroso
17  2024-01-18    31.000     17.30         52.0               0.0   Parcial
18  2024-01-19    30.200     16.80         54.0               0.0   Nublado
19  2024-01-20    29.500     17.50         56.0               0.0   Nublado
20  2024-01-21    28.800     16.20         58.0               0.0  Lluvioso
21  2024-01-22    32.236     17.00         55.0               3.2  Lluvioso
22  2024-01-23    31.500     17.84         52.0               1.5   Parcial
23  2024-01-24    33.200     18.10         49.0               0.0   Soleado
24  2024-01-25    34.000     17.60         47.0               0.0   Soleado
25  2024-01-26    35.100     18.90         44.0               0.0  Caluroso
26  2024-01-27    32.236     19.30         42.0               0.0  Caluroso
28  2024-01-29    31.400     17.20         49.0               0.0   Parcial
29  2024-01-30    30.700     16.90         51.0               0.0   Nublado
30  2024-01-31    29.900     17.40         53.0               0.0   Soleado

In [134]:
#Preguntas de reflexion
#P3.1: mean se utiliza para datos simetricos sin valores extraños, median para datos muy sesgados y valores atipicos como tal
#P3.2: Dos filas de NaN fueron dropeadas, es aceptable debido a que es menor la significancia de perdida de filas para
#Un mejor analisis
#P3.3: Se pierde gran parte de los datos dados, quedando demasiado pocos para un analisis util de algun segmento de investigacion.
#No es factible sin un tratamiento de datos significativo.
a = df.dropna()
print(a)

         fecha  temp_max  temp_min  humedad_pct  precipitacion_mm condicion
0   2024-01-01      32.1      18.2         45.0               0.0   Soleado
1   2024-01-02      33.5      17.5         48.0               0.0   Soleado
5   2024-01-06      35.0      18.5         44.0               0.0  Caluroso
8   2024-01-09      30.5      16.5         55.0               2.5   Nublado
9   2024-01-10      29.8      17.1         53.0               1.8  Lluvioso
10  2024-01-11      31.2      18.3         49.0               0.0  Lluvioso
14  2024-01-15      35.4      19.1         43.0               0.0  Caluroso
17  2024-01-18      31.0      17.3         52.0               0.0   Parcial
18  2024-01-19      30.2      16.8         54.0               0.0   Nublado
19  2024-01-20      29.5      17.5         56.0               0.0   Nublado
20  2024-01-21      28.8      16.2         58.0               0.0  Lluvioso
24  2024-01-25      34.0      17.6         47.0               0.0   Soleado
25  2024-01-26      35.1      18.9         44.0               0.0  Caluroso
28  2024-01-29      31.4      17.2         49.0               0.0   Parcial
29  2024-01-30      30.7      16.9         51.0               0.0   Nublado
30  2024-01-31      29.9      17.4         53.0               0.0   Soleado

In [137]:
#Ejercicio 4

df_limpio[['fecha', 'temp_max', 'condicion']]

         fecha  temp_max condicion
0   2024-01-01    32.100   Soleado
1   2024-01-02    33.500   Soleado
2   2024-01-03    32.236   Parcial
3   2024-01-04    31.800   Soleado
4   2024-01-05    34.200   Soleado
5   2024-01-06    35.000  Caluroso
6   2024-01-07    32.236  Caluroso
7   2024-01-08    33.100   Parcial
8   2024-01-09    30.500   Nublado
9   2024-01-10    29.800  Lluvioso
10  2024-01-11    31.200  Lluvioso
11  2024-01-12    32.236   Parcial
12  2024-01-13    33.700   Soleado
13  2024-01-14    34.900   Soleado
14  2024-01-15    35.400  Caluroso
15  2024-01-16    32.236  Caluroso
17  2024-01-18    31.000   Parcial
18  2024-01-19    30.200   Nublado
19  2024-01-20    29.500   Nublado
20  2024-01-21    28.800  Lluvioso
21  2024-01-22    32.236  Lluvioso
22  2024-01-23    31.500   Parcial
23  2024-01-24    33.200   Soleado
24  2024-01-25    34.000   Soleado
25  2024-01-26    35.100  Caluroso
26  2024-01-27    32.236  Caluroso
28  2024-01-29    31.400   Parcial
29  2024-01-30    30.700   Nublado
30  2024-01-31    29.900   Soleado

In [139]:
df_limpio.iloc[0:5]

        fecha  temp_max  temp_min  humedad_pct  precipitacion_mm condicion
0  2024-01-01    32.100     18.20         45.0               0.0   Soleado
1  2024-01-02    33.500     17.50         48.0               0.0   Soleado
2  2024-01-03    32.236     19.00         42.0               0.0   Parcial
3  2024-01-04    31.800     17.84         50.0               0.0   Soleado
4  2024-01-05    34.200     17.80         49.0               0.0   Soleado

In [141]:
df_limpio.loc[13]

fecha               2024-01-14
temp_max                  34.9
temp_min                  18.7
humedad_pct               49.0
precipitacion_mm           0.0
condicion              Soleado
Name: 13, dtype: object

In [145]:
df_limpio[df_limpio["temp_max"] > 34]

         fecha  temp_max  temp_min  humedad_pct  precipitacion_mm condicion
4   2024-01-05      34.2      17.8         49.0               0.0   Soleado
5   2024-01-06      35.0      18.5         44.0               0.0  Caluroso
13  2024-01-14      34.9      18.7         49.0               0.0   Soleado
14  2024-01-15      35.4      19.1         43.0               0.0  Caluroso
25  2024-01-26      35.1      18.9         44.0               0.0  Caluroso

In [146]:
df_limpio[df_limpio["condicion"] == "Lluvioso"]

         fecha  temp_max  temp_min  humedad_pct  precipitacion_mm condicion
9   2024-01-10    29.800      17.1         53.0               1.8  Lluvioso
10  2024-01-11    31.200      18.3         49.0               0.0  Lluvioso
20  2024-01-21    28.800      16.2         58.0               0.0  Lluvioso
21  2024-01-22    32.236      17.0         55.0               3.2  Lluvioso

In [148]:
#Filtra los días donde temp_max > 30 Y humedad_pct > 50 (condición compuesta).
filtro_compuesto = df_limpio[(df_limpio['temp_max'] > 30) & (df_limpio['humedad_pct'] > 50)]
print(filtro_compuesto)

         fecha  temp_max  temp_min  humedad_pct  precipitacion_mm condicion
7   2024-01-08    33.100     17.84         51.0               0.0   Parcial
8   2024-01-09    30.500     16.50         55.0               2.5   Nublado
17  2024-01-18    31.000     17.30         52.0               0.0   Parcial
18  2024-01-19    30.200     16.80         54.0               0.0   Nublado
21  2024-01-22    32.236     17.00         55.0               3.2  Lluvioso
22  2024-01-23    31.500     17.84         52.0               1.5   Parcial
29  2024-01-30    30.700     16.90         51.0               0.0   Nublado

In [149]:
df_limpio['amplitud_termica'] = df_limpio['temp_max'] - df_limpio['temp_min']
print(df_limpio[['fecha', 'temp_max', 'temp_min', 'amplitud_termica']].head())

        fecha  temp_max  temp_min  amplitud_termica
0  2024-01-01    32.100     18.20            13.900
1  2024-01-02    33.500     17.50            16.000
2  2024-01-03    32.236     19.00            13.236
3  2024-01-04    31.800     17.84            13.960
4  2024-01-05    34.200     17.80            16.400

In [156]:
df_limpio[df_limpio["temp_max"] >= 34]
#P4.1: Predomino principalmente la condición "Soleado" y "Caluroso"
print(df_limpio.describe())
#P4.2: El promedio de la amplitud termina es de 14.364000 y el que mayor tuvo fue de 16.500000
#P4.3: Basicamente hay errores de ejecución y ambiguedad en cuanto a las condiciones.

        temp_max   temp_min  humedad_pct  precipitacion_mm  amplitud_termica
count  29.000000  29.000000    29.000000         29.000000         29.000000
mean   32.204000  17.840000    49.172414          0.310345         14.364000
std     1.788428   0.813722     4.310030          0.827796          1.404882
min    28.800000  16.200000    42.000000          0.000000         12.000000
25%    31.000000  17.300000    46.000000          0.000000         13.236000
50%    32.236000  17.840000    49.000000          0.000000         14.000000
75%    33.500000  18.300000    52.000000          0.000000         15.860000
max    35.400000  19.300000    58.000000          3.200000         16.500000

In [158]:
#Ejercicio 5
dia_caluroso = df_limpio.loc[df_limpio['temp_max'].idxmax()]
print(dia_caluroso)

fecha               2024-01-15
temp_max                  35.4
temp_min                  19.1
humedad_pct               43.0
precipitacion_mm           0.0
condicion             Caluroso
amplitud_termica          16.3
Name: 14, dtype: object

In [160]:
dia_precipitacion = df_limpio.loc[df_limpio['precipitacion_mm'].idxmax()]
print(dia_precipitacion)

fecha               2024-01-22
temp_max                32.236
temp_min                  17.0
humedad_pct               55.0
precipitacion_mm           3.2
condicion             Lluvioso
amplitud_termica        15.236
Name: 21, dtype: object

In [161]:
conteo_condiciones = df_limpio['condicion'].value_counts()
print(conteo_condiciones)

condicion
Soleado     9
Parcial     6
Caluroso    6
Nublado     4
Lluvioso    4
Name: count, dtype: int64

In [163]:
promedio_max = df_limpio['temp_max'].mean()
promedio_min = df_limpio['temp_min'].mean()

print(f"Temperatura máxima promedio: {promedio_max:}°C")
print(f"Temperatura mínima promedio: {promedio_min:}°C")

Temperatura máxima promedio: 32.204°C
Temperatura mínima promedio: 17.839999999999996°C

In [165]:
total_duplicados = df_limpio.duplicated().sum()
print(f"Cantidad de días duplicados: {total_duplicados}")

Cantidad de días duplicados: 0

In [166]:
resumen_final = df_limpio.describe(include=['float64'])
print(resumen_final)

        temp_max   temp_min  humedad_pct  precipitacion_mm  amplitud_termica
count  29.000000  29.000000    29.000000         29.000000         29.000000
mean   32.204000  17.840000    49.172414          0.310345         14.364000
std     1.788428   0.813722     4.310030          0.827796          1.404882
min    28.800000  16.200000    42.000000          0.000000         12.000000
25%    31.000000  17.300000    46.000000          0.000000         13.236000
50%    32.236000  17.840000    49.000000          0.000000         14.000000
75%    33.500000  18.300000    52.000000          0.000000         15.860000
max    35.400000  19.300000    58.000000          3.200000         16.500000

In [167]:
#P5.1:La condición predominante fue Soleado (con 11 días), seguida de "Parcial" y "Caluroso". Así que, se puede determinar que si
#P5.2: Sí, es consistente, debido a que la temperatura en talca se acerca a tales temperaturas en el mes
#P5.3: Tal vez utilizando gráficos más visuales para que la persona pueda entenderlo de mejor manera.